version: '2'
services:
  db:
    restart: always
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - docker/db.env
    volumes:
      - postgres_vol:/var/lib/postgresql/data/
  web:
    restart: always
    expose:
      - "8000"
    build: web
    env_file:
      - docker/web.env
      - docker/db.env
    command: /app/web_entrypoint.sh
    volumes:
      - /app/static
    links:
      - db:db
      - redis:redis

  nginx:
    restart: always
    build: ./nginx/
    volumes:
      - /www/static
    volumes_from:
      - web
    links:
      - web:web

  redis:
    restart: always
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_vol:/data

volumes:
  postgres_vol:
  redis_vol: